# Goal Point

# Request
motion_controller_pkg/GoalCommand goal_command          # Goal command message
---
# Result
bool success                                            # Point reached?
---
# Feedback
geometry_msgs/PoseStamped current_pose                  # Current pose (m)
geometry_msgs/TwistStamped current_speed                # Current speed (m/s)